### ISSUE TITLE
Concept / Background Reading

### ISSUE THREAD

**Issue by samouri** [FriteGames/udpeer#1]
**Summary**
Straight up UDP is impossible in browsers, yet essential for any highly real time applications.
For a real-time game, TCP is unacceptable unless in ideal network conditions (100ms latency 0% packet loss).

There is a protocol called WebRTC meant for p2p connections between browsers. It was designed for things like video/voice chat, file transfer, etc and requires at least a signalling server (STUN) in order to connect peers. The super interesting bit here is that WebRTC allows for the creation of _data channels_. These channels behave similarly to websockets, and are allowed to be configured to have _unordered and unreliable packet delivery_.

The protocol has been designed purely for the p2p case and implementing a server/client architecture though it is incredibly awkward (the libs are pretty awkward _even_ for the usecase they were built for).

I think it should be possible to build an api on top of WebRTC libs that would let us create an easy to use UDP-like connection in a client/server model. 

**Background Reading**
 - [Peering though the WebRTC Fog](https://hacks.mozilla.org/2015/04/peering-through-the-webrtc-fog-with-socketpeer/): Background on the complexities of the standard.
- [HumbleNet](https://hacks.mozilla.org/2017/06/introducing-humblenet-a-cross-platform-networking-library-that-works-in-the-browser/): C based lib that works with WebRTC and gets compiled via emscripten
- [SimplePeer](https://github.com/feross/simple-peer): the best looking lib for radically simplifying WebRTC usage. Also works in Node.js. Currently supports only a single customizable data-channel.
  - [SimplePeer Multiplex Support](https://github.com/feross/simple-peer/issues/19): approved by maintainer. Just awaiting a PR.
- [Deterministic Lockstep](https://gafferongames.com/post/deterministic_lockstep/): Gaffer On Games discussing deterministic lockstep and just how much better UDP is than TCP.
- [TCP vs. UDP](https://gafferongames.com/post/udp_vs_tcp/): Gaffer on Games discussing TCP vs. UDP at length. The interesting bit is that mixing UDP and TCP can induce packet loss for UDP. ew.
- [Multiplayer Networking](https://developer.valvesoftware.com/wiki/Source_Multiplayer_Networking): also [this one](https://developer.valvesoftware.com/wiki/Latency_Compensating_Methods_in_Client/Server_In-game_Protocol_Design_and_Optimization#Overview). Valve covering the basics for how to handle latency in a game.

**Comment by zachlite** [comment]
Background on client server networking mechanics
http://www.gabrielgambetta.com/client-server-game-architecture.html

**Comment by samouri** [comment]
@zachlite: hows the `udpeer` research going?
